version: '3.8'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - data:/data/db
  
  backend:
    build: ./backend
    ports:
      - 9947:9947
    depends_on:
      - mongo

  
volumes:
  data:
